### ISSUE TITLE
Mission Row Gate

### ISSUE THREAD

**Issue by stickybombz** [ESX-PUBLIC/esx_doorlock#3]
I added the YMAP that you reference in the new update, and you can see the option to lock and unlock on the gate but it still opens when you get close and can walk/drive right through
![mission row](https://user-images.githubusercontent.com/38120099/43179022-8f478f2c-8f9e-11e8-8933-4b423cce7540.png)

**Comment by stickybombz** [comment]
I just redownloaded it, and it still has the same result

**Comment by ElPumpo** [comment]
This script currently only supports the old version of the map. Here is a re-up since the author removed the old versions from the website: [Mission Row Gate v1.1.zip](https://github.com/ESX-PUBLIC/esx_celldoors/files/2227719/Mission.Row.Gate.v1.1.zip)

**Comment by HumanTree92** [comment]
I have made my own ymap which i have added gates & i have not had a single problem. Sometimes i will notice that if another person unlocks the gate it will tell me that its locked. But for him it would open & for me it wouldn't. Not a huge problem.

**Comment by stickybombz** [comment]
HumanTree could you possibly send me that map

**Comment by HumanTree92** [comment]
https://github.com/HumanTree92/FiveM_CustomMapAddons

Its the Policing Dept Upgrades. But it adds gate to Paleto, Sandy Shores, & Mission Row. It also adds lighting & some small other things to make them look better. I am still working on it but i update on my github when i add something new. Also on the Mission Row the Fencing around it got glitched somehow but i am working on fix that.

**Comment by Ultrunz** [comment]
@stickybombz if you want to use that first map I edited it for me :)
```
	-- Entrance Gate (Mission Row mod) https://www.gta5-mods.com/maps/mission-row-pd-ymap-fivem-v1
	{
		objName = 'Prop_Gate_airport_01',
		objCoords  = {x = 411.94, y = -1025.39, z = 29.33},
		textCoords = {x = 412.64, y = -1021.49, z = 32.00},
		authorizedJobs = { 'police' },
		locked = true,
		distance = 14,
		size = 2
	}
```

**Comment by Ultrunz** [comment]
Added the side door for the carpark :)

```
	-- Side Door (Mission Row mod) https://www.gta5-mods.com/maps/mission-row-pd-ymap-fivem-v1
	{
		objName = 'v_ilev_cor_doorglassb',
		objCoords  = {x = 253.3, y = -1360.87, z = 24.54},
		textCoords = {x = 253.3, y = -1360.87, z = 25.00},
		authorizedJobs = { 'ambulance', 'police' },
		locked = true,
		distance = 2.5
	},
```

**Comment by Peltori** [comment]
![stikgkw](https://user-images.githubusercontent.com/46245016/50540067-d3061500-0b93-11e9-8c5f-aaf7e881ad57.jpg)
this gate is what i meant

**Comment by HumanTree92** [comment]
-- Mission Row PD Parking Lot Gate
	{
		objName = 'prop_gate_military_01',
		objCoords  = {x = 415.71, y = -1024.84, z = 28.14},
		textCoords = {x = 415.71, y = -1024.84, z = 30.14},
		authorizedJobs = { 'police' },
		locked = true,
		distance = 14,
		size = 2
	},

**Comment by HumanTree92** [comment]
@Peltori  I have also updated my github for all the cords for my map addons.

**Comment by Peltori** [comment]
thank man appreciate the help very much :)
