### ISSUE TITLE
Add door

### ISSUE THREAD

**Issue by btwentyone** [ESX-PUBLIC/esx_doorlock#9]
Hello, here is my contribution to the code ;-)

Remember to change the profession for gov if it's another name
	

      --
	-- Ls custom
	--
	{
		objName = 'lr_prop_supermod_door_01',
		objCoords  = {x = -205.6828, y = -1310.683, z = 30.29572},
		textCoords = {x = -205.6828, y = -1310.683, z = 31.29572},
		authorizedJobs =  { 'mecano' },
		locked = true,
		distance = 16.5
	},
	
	--
	-- Unicorn
	--
	{
		objName = 'v_ilev_door_orangesolid',
		objCoords  = {x = 113.7693, y = -1296.6870, z = 28.2687},
		textCoords = {x = 113.7693, y = -1296.6870, z = 29.2687},
		authorizedJobs =  { 'unicorn' },
		locked = true,
		distance = 2.5
	},
	
	{
		objName = 'prop_magenta_door',
		objCoords  = {x = 95.4944, y = -1285.2659, z = 28.7763},
		textCoords = {x = 95.4944, y = -1285.2659, z = 29.7763},
		authorizedJobs =  { 'unicorn' },
		locked = true,
		distance = 2.5
	},
	
		{
		objName = 'v_ilev_roc_door2',
		objCoords  = {x = 99.7319, y = -1293.2723, z = 28.2687},
		textCoords = {x = 99.7319, y = -1293.2723, z = 29.2687},
		authorizedJobs =  { 'unicorn' },
		locked = true,
		distance = 2.5
	},
	
	--
	-- banker
	--
	{
		objName = 'v_ilev_bk_door',
		objCoords  = {x = 265.6144, y = 217.7971, z = 109.2830},
		textCoords = {x = 265.6144, y = 217.7971, z = 110.2830},
		authorizedJobs =  { 'banker' },
		locked = true,
		distance = 2.5
	},
	
	{
		objName = 'v_ilev_bk_door',
		objCoords  = {x = 256.9125, y = 206.8366, z = 109.2830},
		textCoords = {x = 256.9125, y = 206.8366, z = 110.2830},
		authorizedJobs =  { 'banker' },
		locked = true,
		distance = 2.5
	},
	
	--
	-- cardealer
	--
	{
		objName = 'v_ilev_fib_door1',
		objCoords  = {x = -31.9621, y = -1102.4952, z = 25.4223},
		textCoords = {x = -31.9621, y = -1102.4952, z = 26.4223},
		authorizedJobs =  { 'cardealer' },
		locked = true,
		distance = 2.5
	},
	
	{
		objName = 'v_ilev_fib_door1',
		objCoords  = {x = -34.0121, y = -1108.2611, z = 25.4223},
		textCoords = {x = -34.0121, y = -1108.2611, z = 26.4223},
		authorizedJobs =  { 'cardealer' },
		locked = true,
		distance = 2.5
	},
	
	--
	-- gouv "FIB"
	--
	
	{
		objName = 'v_ilev_fib_door2',
		objCoords  = {x = 146.7166, y = -755.5300, z = 241.1519},
		textCoords = {x = 146.7166, y = -755.5300, z = 242.1519},
		authorizedJobs =  { 'gouvernor' },
		locked = true,
		distance = 2.5
	},
	
	{
		objName = 'v_ilev_fib_door2',
		objCoords  = {x = 138.7746, y = -768.1416, z = 241.1521},
		textCoords = {x = 138.7746, y = -768.1416, z = 242.1521},
		authorizedJobs =  { 'gouvernor' },
		locked = true,
		distance = 2.5
	},
	
	{
		objName = 'v_ilev_fib_door2',
		objCoords  = {x = 127.4972, y = -763.9457, z = 241.1520},
		textCoords = {x = 127.4972, y = -763.9457, z = 242.1520},
		authorizedJobs =  { 'gouvernor' },
		locked = true,
		distance = 2.5
	},
	
	{
		objName = 'v_ilev_fib_door2',
		objCoords  = {x = 151.2399, y = -742.8903, z = 241.1519},
		textCoords = {x = 151.2399, y = -742.8903, z = 242.1519},
		authorizedJobs =  { 'gouvernor' },
		locked = true,
		distance = 2.5
	},
	
	{
		objName = 'v_ilev_fib_door2',
		objCoords  = {x = 152.7519, y = -738.8159, z = 241.1519},
		textCoords = {x = 152.7519, y = -738.8159, z = 242.1519},
		authorizedJobs =  { 'gouvernor' },
		locked = true,
		distance = 2.5
	},
	
	{
		objName = 'v_ilev_fib_door2',
		objCoords  = {x = 121.2496, y = -756.9983, z = 241.1519},
		textCoords = {x = 121.2496, y = -756.9983, z = 242.1519},
		authorizedJobs =  { 'gouvernor' },
		locked = true,
		distance = 2.5
	},
	
	{
		objName = 'v_ilev_fib_door2',
		objCoords  = {x = 119.0227, y = -734.0013, z = 241.1520},
		textCoords = {x = 119.0227, y = -734.0013, z = 242.1520},
		authorizedJobs =  { 'gouvernor' },
		locked = true,
		distance = 2.5
	},

**Comment by Ultrunz** [comment]
Nice work dude! I will be taking this for mine too. I added the hospital and some more doors at the mission row PD. Theyre in different 'issues' though

**Comment by ElPumpo** [comment]
1. why is this an issue?! make it a PR instead???
2. there's NO documentation on what doors these are. I'm not interested of doing extra work
